# Generated by Django 6.0.2 on 2026-02-06 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOfGrading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('photo', models.URLField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('object_name', models.CharField(blank=True, max_length=100, null=True)),
                ('objects_name', models.CharField(blank=True, max_length=100, null=True)),
                ('note_name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Класс оценки',
                'verbose_name_plural': 'Классы оценки',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('canonical_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_objects', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Глобальный класс',
                'verbose_name_plural': 'Глобальные классы',
                'ordering': ['-total_users', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Доказательство',
                'verbose_name_plural': 'Доказательства',
            },
        ),
        migrations.CreateModel(
            name='RankType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('from_rank', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип ранга',
                'verbose_name_plural': 'Типы рангов',
                'ordering': ['-from_rank'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Рабочее пространство',
                'verbose_name_plural': 'Рабочие пространства',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=1)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_of_grading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='grading.classofgrading')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='classofgrading',
            name='global_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_instances', to='grading.globalclass'),
        ),
        migrations.CreateModel(
            name='GradeObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('photo', models.URLField(blank=True, null=True)),
                ('object_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('overall_rank', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_of_grading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_objects', to='grading.classofgrading')),
            ],
            options={
                'verbose_name': 'Оцениваемый объект',
                'verbose_name_plural': 'Оцениваемые объекты',
                'ordering': ['-overall_rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.URLField()),
                ('media_type', models.CharField(max_length=50)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail_uri', models.URLField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='grading.gradeobject')),
            ],
            options={
                'verbose_name': 'Медиа-элемент',
                'verbose_name_plural': 'Медиа-элементы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('photo_uri', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='grading.gradeobject')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryOfObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='grading.category')),
                ('grade_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='grading.gradeobject')),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_proofs', to='grading.proof')),
            ],
            options={
                'verbose_name': 'Оценка по категории',
                'verbose_name_plural': 'Оценки по категориям',
            },
        ),
        migrations.CreateModel(
            name='ClassRankType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_of_grading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_rank_types', to='grading.classofgrading')),
                ('rank_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_classes', to='grading.ranktype')),
            ],
            options={
                'verbose_name': 'Тип ранга класса',
                'verbose_name_plural': 'Типы рангов классов',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=1)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='grading.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoryOfObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_of_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_ratings', to='grading.categoryofobject')),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_proofs', to='grading.proof')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_ratings', to='grading.subcategory')),
            ],
            options={
                'verbose_name': 'Оценка по подкатегории',
                'verbose_name_plural': 'Оценки по подкатегориям',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tags', to='grading.tag')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_tags', to='grading.gradeobject')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_objects', to='grading.tag')),
            ],
            options={
                'verbose_name': 'Тег объекта',
                'verbose_name_plural': 'Теги объектов',
            },
        ),
        migrations.CreateModel(
            name='ClassTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_of_grading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_tags', to='grading.classofgrading')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_classes', to='grading.tag')),
            ],
            options={
                'verbose_name': 'Тег класса',
                'verbose_name_plural': 'Теги классов',
            },
        ),
    ]
