# Generated by Django 6.0.2 on 2026-02-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkspace',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='grading.userworkspace'),
        ),
        migrations.AddField(
            model_name='ranktype',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_types', to='grading.userworkspace'),
        ),
        migrations.AddField(
            model_name='classofgrading',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_classes', to='grading.userworkspace'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryofobject',
            unique_together={('category', 'grade_object')},
        ),
        migrations.AlterUniqueTogether(
            name='classranktype',
            unique_together={('class_of_grading', 'rank_type')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategoryofobject',
            unique_together={('subcategory', 'category_of_object')},
        ),
        migrations.AlterUniqueTogether(
            name='objecttag',
            unique_together={('grade_object', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='classtag',
            unique_together={('class_of_grading', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('workspace', 'name', 'parent_tag')},
        ),
        migrations.AlterUniqueTogether(
            name='ranktype',
            unique_together={('workspace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classofgrading',
            unique_together={('workspace', 'name')},
        ),
    ]
