# Generated by Django 6.0.2 on 2026-02-11 15:03

import grading.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_alter_category_id_alter_categoryofobject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoryofobject',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classofgrading',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classranktype',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classtag',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='globalclass',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gradeobject',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='objecttag',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proof',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ranktype',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategoryofobject',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userworkspace',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
