# Generated by Django 6.0.2 on 2026-02-10 10:58

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_avatar_path, verbose_name='Фото профиля'),
        ),
    ]
