# Generated by Django 6.0.2 on 2026-02-06 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('canonical_name', models.CharField(db_index=True, max_length=300)),
                ('total_ratings', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_objects', to='grading.globalclass')),
            ],
            options={
                'verbose_name': 'Глобальный объект',
                'verbose_name_plural': 'Глобальные объекты',
                'ordering': ['-average_rating', '-total_ratings'],
            },
        ),
        migrations.CreateModel(
            name='GlobalLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, default='all-time', max_length=50)),
                ('rank_value', models.FloatField()),
                ('total_users', models.IntegerField(default=0)),
                ('category_stats', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='leaderboard.globalobject')),
            ],
            options={
                'verbose_name': 'Запись глобального рейтинга',
                'verbose_name_plural': 'Записи глобального рейтинга',
                'ordering': ['-rank_value'],
            },
        ),
        migrations.CreateModel(
            name='GlobalCategoryLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_index=True, max_length=200)),
                ('canonical_category_name', models.CharField(db_index=True, max_length=200)),
                ('average_rank', models.FloatField()),
                ('total_ratings', models.IntegerField(default=0)),
                ('period', models.CharField(default='all-time', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_leaderboards', to='leaderboard.globalobject')),
            ],
            options={
                'verbose_name': 'Категорийный рейтинг',
                'verbose_name_plural': 'Категорийные рейтинги',
                'ordering': ['-average_rank'],
            },
        ),
        migrations.CreateModel(
            name='PopularTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(db_index=True, max_length=100)),
                ('canonical_tag_name', models.CharField(db_index=True, max_length=100)),
                ('usage_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_tags', to='grading.globalclass')),
            ],
            options={
                'verbose_name': 'Популярный тег',
                'verbose_name_plural': 'Популярные теги',
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='TrendingObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(default='7days', max_length=50)),
                ('new_ratings_count', models.IntegerField(default=0)),
                ('rating_velocity', models.FloatField(default=0.0)),
                ('trending_score', models.FloatField()),
                ('trending_rank', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('global_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_entries', to='leaderboard.globalobject')),
            ],
            options={
                'verbose_name': 'Трендовый объект',
                'verbose_name_plural': 'Трендовые объекты',
                'ordering': ['-trending_score'],
            },
        ),
        migrations.CreateModel(
            name='UserObjectContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_public', models.BooleanField(default=True)),
                ('last_synced_rank', models.FloatField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('global_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contributions', to='leaderboard.globalobject')),
                ('grade_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_contribution', to='grading.gradeobject')),
            ],
            options={
                'verbose_name': 'Вклад пользователя',
                'verbose_name_plural': 'Вклады пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserRatingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_rank', models.FloatField(blank=True, null=True)),
                ('new_rank', models.FloatField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('grade_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to='grading.gradeobject')),
            ],
            options={
                'verbose_name': 'История оценок',
                'verbose_name_plural': 'История оценок',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='globalobject',
            index=models.Index(fields=['global_class', '-average_rating'], name='leaderboard_global__bb0a93_idx'),
        ),
        migrations.AddIndex(
            model_name='globalobject',
            index=models.Index(fields=['global_class', '-total_ratings'], name='leaderboard_global__fa0f9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='globalobject',
            unique_together={('global_class', 'canonical_name')},
        ),
        migrations.AddIndex(
            model_name='globalleaderboard',
            index=models.Index(fields=['period', '-rank_value'], name='leaderboard_period_7196fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='globalleaderboard',
            unique_together={('global_object', 'period')},
        ),
        migrations.AddIndex(
            model_name='globalcategoryleaderboard',
            index=models.Index(fields=['canonical_category_name', '-average_rank'], name='leaderboard_canonic_2fe9eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='globalcategoryleaderboard',
            unique_together={('global_object', 'canonical_category_name', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='populartag',
            unique_together={('global_class', 'canonical_tag_name')},
        ),
        migrations.AddIndex(
            model_name='trendingobject',
            index=models.Index(fields=['period', '-trending_score'], name='leaderboard_period_6f94cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trendingobject',
            unique_together={('global_object', 'period')},
        ),
        migrations.AddIndex(
            model_name='userobjectcontribution',
            index=models.Index(fields=['global_object', 'is_public'], name='leaderboard_global__eb5360_idx'),
        ),
        migrations.AddIndex(
            model_name='userratinghistory',
            index=models.Index(fields=['grade_object', '-changed_at'], name='leaderboard_grade_o_2d17d9_idx'),
        ),
    ]
