# Generated by Django 6.0.2 on 2026-02-11 15:03

import grading.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcategoryleaderboard',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='globalleaderboard',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='globalobject',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='populartag',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trendingobject',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userobjectcontribution',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userratinghistory',
            name='id',
            field=models.CharField(default=grading.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
